import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Link from "next/link";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, team, analytics}: Readonly<{
  children: React.ReactNode;
  team: React.ReactNode;
  analytics: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressContentEditableWarning={false}>
      <body>
      <AntdRegistry>
          <div className="container mx-auto">
              <div className="flex justify-center text-blue-300 p-6 gap-6">
                  <Link href="/">Home</Link>
                  <Link href="/visitors">Visitors</Link>
              </div>
              <div className='flex gap-6'>
                  {team}
                  {analytics}
              </div>
              {children}
          </div>
          </AntdRegistry>
      </body>
    </html>
  );
}
